"""Art direction phase 2: the bestiary's briefs under docs/ART_DIRECTION.md (moonlit ink and wash, one BLOOD accent).
Written into art/manifest.json as `brief3` (python3 art/phase2_briefs.py); make_prompts.build3 prefers it over `description`.
Each keeps the v2 brief's tag (ART.md: the tag lives in the silhouette); colours are the guide's palette names."""
import json
from pathlib import Path

GOB = "cold DUSK-green goblin skin (a desaturated grey-green inside the DUSK/MOON family, NOT bright green), long pointed ears with MIST rims, small glinting BONE eyes, INK shadow"
DEAD = ("DEATH POSE of {who}, the same character as its living boss sprite: fallen and lying still, seen from the same high "
        "three-quarter camera, the body stretched out HORIZONTALLY (on its side or back, head to the right), limbs slack, its weapon "
        "dropped beside it, crown knocked askew. It must read as 'the boss, dead' — a recognisable body, not a smear: keep its "
        "signature shapes and colours, the living colours sunk a step toward UMBRA, moonlight on the top edges only. Wide and low: "
        "the body spans most of the canvas width and about a third of its height. A small BLOOD spatter near the wound is allowed; "
        "NO blood pool, no floor, no shadow.")

B = {
 "rat": "A big dungeon RAT seen from the SIDE, facing right, the body stretched LONG and low (twice as long as tall): matted UMBRA-and-DUSK fur with MIST rims along the spine, a pointed snout, one glinting BONE eye, round ears lined with a touch of CLOT, and a long bare tail in a single curve (a dull BONE-pink wash). TAG: the long body and the tail — reads 'rat' at 20 px.",
 "jackal": "A lean dungeon JACKAL facing right mid-lope: low horizontal body, ribs showing, big pointed ears, narrow snarling snout with BONE teeth, tail straight out behind. Dusty DUSK-and-MOON fur (the place's tint), MIST rims along the back, INK belly shadow. TAG: LOW, LEAN, FAST — a stretched horizontal dash with ears. Reads at 24 px.",
 "goblin": f"A small hunched GOBLIN facing right: big head, {GOB}, wide grin of BONE teeth, pot belly, a crude short CLEAVER raised at shoulder height (its edge a MIST rim), a rag loincloth of UMBRA cloth. TAG: goblin with a raised cleaver — compact upright silhouette at 40 px.",
 "goblin_archer": f"A GOBLIN ARCHER facing right, DRAWING A BOW: {GOB}; a tall crude recurve bow held out front, the string (a thin MIST line) pulled fully back to the cheek, an arrow nocked, a quiver on the back, a leather cap. TAG: the drawn bow is a big clear arc WIDER than the body at 40 px.",
 "goblin_conjurer": f"A GOBLIN CONJURER facing right: the goblin build ({GOB}), a tattered DUSK-violet robe with a bone-fetish hood, both arms raised holding a gnarled staff overhead; two small pale MIST ghost-blades hover just above the staff tip. TAG: raised staff + hovering blades — a T-shape with two pale sparks at 40 px.",
 "goblin_captain": f"A goblin CAPTAIN facing right, a head taller and broader than a plain goblin: {GOB}; a dented iron half-helm with two short horns (MIST rims), a battered war HORN raised to its mouth in one hand (it summons), a notched short sword low in the other, a scale-mail vest, a BLOOD sash (its one accent). TAG: the raised horn and the horned helm — 'the goblin that calls the others' at 48 px.",
 "monkey": "A mischievous dungeon MONKEY facing right, mid-scamper on three limbs, CLUTCHING a stolen bulging SACK (pale BONE canvas, the brightest thing, tied with a CLOT cord) against its chest, a long tail curled up in a question mark, a cheeky grin. UMBRA-and-DUSK fur with MIST rims, a paler belly. TAG: the pale sack and the tail. Reads at 28 px.",
 "ogre": "A HUGE wide OGRE facing right, winding up: massive rounded shoulders, a small head, a barrel gut, a great tree-trunk CLUB raised high over its head in both hands. Cold grey-DUSK hide with MOON lights and MIST rims on the shoulders, a ragged hide kilt, BONE tusks. TAG: HUGE and heavy, the club overhead — a broad mass much wider than a goblin at 48 px.",
 "bloat": "A BLOAT: one swollen, taut, floating SAC of sickly pale teal-green gas (its one local hue, a washed MIST-green, lit from within), veined in DUSK, a few tiny dangling tendrils and a small puckered INK mouth. No limbs, no face. TAG: SWOLLEN SAC — one fat teardrop/balloon silhouette. Reads 'about to pop' at 40 px.",
 "pink_jelly": "A PINK JELLY: a low translucent quivering BLOB, a dome with a wobbly lower edge, in pale watery CLOT-rose washes (its one local hue, muted, never candy pink) with BONE highlights where the moon catches its top, a few darker CLOT flecks suspended inside. No face, no limbs. TAG: TRANSLUCENT BLOB — a squat dome. Reads at 24 px.",
 "eel": "A dungeon EEL facing right: a long thick S-CURVED body rising as if out of water, jaws open with BONE needle teeth, a fin ridge along the back, the tail trailing off lower-left. INK-and-DUSK back with a cold teal sheen (its local hue, inside the MOON family), a BONE belly, MIST rims. TAG: the long S-curve with a mouth. Reads at 20 px.",
 "skeleton": "A walking SKELETON warrior facing right: ALL BONE, upright, the ribcage and skull clearly drawn in BONE washes with MIST rims, INK between every bone, a rusted notched sword, a few rags of UMBRA grave-cloth. TAG: ALL BONE — the gappy ribcage silhouette. Reads at 48 px.",
 "ghoul": "A GHOUL facing right: HUNCHED and gaunt, grey DUSK corpse flesh with MOON lights, arms out front ending in long clawed hands (BONE claws), jaw hanging open, lank INK hair. TAG: HUNCHED with CLAWS reaching forward — the silhouette leans forward, two claw shapes leading. Distinct from the upright skeleton at 40 px.",
 "wraith": "A WRAITH facing right, a GHOST: a tall floating tattered SHROUD with no legs, the hem torn into long trailing ribbons, drawn mostly in MIST and BONE washes (translucent, paper showing through), a hooded INK void for a face with two pale points, one long clawed reaching hand, wisps trailing. TAG: TATTERED and FLOATING — ragged hem, no feet. Reads at 48 px.",
 "captive": "A CAPTIVE facing right: a young adventurer kneeling, slumped, looking up hopefully; heavy iron manacles and ONE thick dark iron CHAIN looping across the whole figure from the wrists to the ground (INK links with MIST glints); torn DUSK tunic, a pale BONE face. TAG: IN CHAINS — the chain a bold dark loop in the silhouette at 48 px.",
 "spectral_blade": "A SPECTRAL BLADE: a single floating ghost-sword, point down, drawn in MIST and BONE washes (translucent, glowing cold), a faint trailing wisp, a bold INK outline. TAG: a floating sword — a vertical blade at 20 px.",
 "spectral_hound": "A SPECTRAL HOUND facing right: a lean running dog of MIST and BONE wash (translucent, cold), the hind legs fading into wisps, ears back, mouth open, a bold INK outline. TAG: a ghostly running dog. Reads at 20 px.",
 "iron_golem": "An IRON GOLEM facing right, MASSIVE and boxy: a walking stack of thick riveted iron plates in INK/DUSK with MOON lights and MIST rims on every top edge, slab shoulders wider than it is tall at the top, a small visor-slit head sunk between them, block forearms, stubby plated legs; thin EMBER seams between the plates painted as flat bright cracks (no glow cloud). TAG: MASSIVE IRON PLATES — a squared-off stepped block, all right angles. Reads at 48 px.",
 "forge_imp": "A FORGE IMP facing right, SMALL, mid-hop with knees tucked: a scrawny imp with EMBER-orange skin (its local hue — it lives by the forge) and INK soot hands, feet and horn tips, one small flame tuft of hair (the body is flesh, NOT fire), a wide toothy grin, HOLDING OUT a stolen round-bellied POTION FLASK of pale BONE glass in both arms, the flask a third of its height, separated by a full INK contour — the palest thing in the sprite. TAG: SMALL, WITH A STOLEN BOTTLE — a pale round bump on the front at 28 px.",
 "bell_sentinel": "A BELL SENTINEL facing right, upright and stiff: an iron-armoured humanoid (INK/DUSK iron, MIST rims) whose entire HEAD IS A LARGE BELL of worn GILT bronze, the flared mouth opening down over the shoulders, wider than the body, a dark clapper inside; a slender riveted body; one arm raised with a striking rod. TAG: A BELL FOR A HEAD — unmistakable at 40 px.",
 "slag_crawler": "A SLAG CRAWLER facing right: LOW and long, many-legged, a crust of cooled INK slag cracked open along the back to show EMBER heat beneath (flat bright cracks), a blunt heavy head low in front, six stubby legs, and a TRAIL OF EMBERS off the tapering tail (small EMBER and BONE flecks, part of the silhouette). TAG: LOW and TRAILING EMBERS — a horizontal dash with a dotted ember tail. Reads at 24 px.",
 "smith": "A foundry SMITH facing right, stocky and broad: bare arms in DUSK skin with MOON lights, a heavy UMBRA leather APRON down to the shins, a massive square-headed HAMMER raised in both hands over the shoulder (MIST rim on its head), a soot-streaked face with a set jaw and a headband, thick gloves, one EMBER hot rivet on the apron. TAG: HAMMER AND APRON — the raised square hammer and the long apron rectangle at 40 px.",
 "lurker": "A LURKER facing right, hunched: a pallid BONE-white cave-thing with NO EYES — a smooth blank brow over a wide lipless mouth of needle teeth — a long neck craned forward, and ARMS FAR LONGER THAN ITS BODY hanging down past its feet, long thin fingers; MIST lights, DUSK/INK shadow side. TAG: EYELESS and LONG-ARMED — a hunched body with two arms hanging to the bottom edge. Reads at 40 px.",
 "deep_eel": "A DEEP EEL facing right: a very long thin RIBBON of a fish undulating in three waves across the frame, a continuous translucent MIST fin frill along the whole back, a narrow head with a needle jaw at the right, a tapering tail at the left. INK back, BONE belly, a few pale MIST flecks along the flank. TAG: A RIBBON — thin and wavy, clearly not the thick S-curved eel. Reads at 24 px.",
 "cave_troll": "A CAVE TROLL facing right: HUNCHED BULK — an enormous rounded back and shoulders, a small head sunk low in front of the chest, long thick arms with knuckles at ankle level, short bowed legs, no weapon. Mottled DUSK-and-MOON hide with wart lumps, MIST rims along the boulder back, a paler BONE-grey belly. TAG: HUNCHED BULK — a boulder with knuckles under it, clearly not the upright ogre. Reads at 48 px.",
 "siren": "A SIREN facing right, standing and SINGING: a slender figure in a long INK-and-DUSK robe, NO HOOD — a bare head with long flowing dark hair, the whole head TILTED BACK so the face points at the ceiling, the mouth open wide in song, both arms spread wide and low; THREE thick pale MIST sound-arcs rising from the open mouth (flat shapes, each as thick as the contour). A pale BONE face and throat. TAG: the upturned singing face and the arcs are the top of the silhouette. Distinct from the floating wraith: she stands.",
 "mirror_shade": "A MIRROR SHADE facing right: the hero's DARK REFLECTION — a clear standing HUMAN hero silhouette in a wide fighting stance (legs apart), a LONG straight sword held out low and forward past the body, a short tattered half-cloak; the whole figure a flat INK/UMBRA shape with bright MIST edge light along its top and left contours, NO face, one pale BONE crack across the chest, a thin CLOT lining in the cloak (the hero's red, drained). TAG: A HERO SHAPE, BUT DARK. Reads at 48 px.",
 "warden": "A sanctum WARDEN facing right, tall and upright in pale BONE-and-MIST plate armour with GILT trim and a DUSK tabard: a tall rectangular TOWER SHIELD held out in FRONT covering knees to chin, a LONGBOW slung across the BACK so its arc pokes above the far shoulder and below the hip, a quiver beside it; a closed great-helm. TAG: SHIELD IN FRONT, BOW ON THE BACK — two distinct bumps at 48 px.",
 "acolyte": "A sanctum ACOLYTE facing right, BOWED: a robed figure bent forward at the waist, head bowed low, both arms raised with open palms up at shoulder height (an offering), a long BONE-white robe with a GILT hem and a DUSK hood, bare feet. TAG: BOWED, HANDS UP — a folded figure with two raised hands, clearly not the singing siren. Reads at 40 px.",
 "echo": "An ECHO facing right: a slender pale humanoid in a plain BONE tunic drawn TWICE — the front figure solid, an identical DOUBLE offset half a body-width up and left behind it painted as a translucent MIST ghost with its own INK outline; both in the same walking pose. TAG: A TRANSLUCENT DOUBLE — two heads and two sets of legs at 40 px.",
 "sentinel": "A sanctum SENTINEL: a squat standing STONE PILLAR, slightly tapered, pale BONE-grey stone with MIST lights and DUSK shadow, ONE HUGE OPEN EYE carved into its upper face — a wide almond eye with a GILT iris and an INK pupil, looking right — a few GILT inlay lines below. No limbs. TAG: A STONE EYE — a blunt monolith with an eye. Reads at 40 px.",
 "boss_goblin_warlord": f"The GOBLIN WARLORD facing right, a BOSS far larger than any goblin: a towering gaunt goblin king, {GOB}, a long tattered BLOOD-and-INK MANTLE flaring behind (its one accent), an iron CROWN of spikes with MIST rims, a few scavenged iron plates, a huge CLEAVER in one hand, the other a raised clawed fist, glowing BONE eyes. TAG: BOSS — crowned, big, the blood mantle. Reads as 'the big crowned goblin' at 64 px.",
 "boss_bloat_mother": "The BLOAT MOTHER: an enormous swollen SAC of sickly pale teal-green gas (the bloat's local hue, a washed MIST-green lit from within), veined in DUSK, ringed at the top with a CROWN of BONE spines, dozens of tiny bloat-buds budding from her sides, a wide puckered INK maw. TAG: BOSS — huge, spine-crowned, budding: a giant balloon with a spiky crown at 64 px.",
 "boss_lich": "The LICH facing right: a tall gaunt robed skeleton king in tattered INK-and-DUSK robes, a tall BONE SKULL-CROWN, one hand raising a crooked staff topped with a pale skull, the other hand open holding a cold MIST-white flame (magic glows MIST). BONE skull, MIST rims. TAG: BOSS — crowned skull, staff, cold flame. Reads at 64 px.",
 "boss_foundry_master": "The FOUNDRY MASTER facing right, larger than the iron golem: a colossal forge-lord of riveted INK/DUSK iron with MIST rims and worn GILT bronze trims, an ANVIL-SHAPED chest, a heavy UMBRA leather apron over the plates, a jagged CROWN of iron rivet-spikes, a gigantic two-handed forge HAMMER raised overhead, EMBER seams at every joint (flat bright cracks). TAG: BOSS — crowned, huge hammer, apron over iron. Reads at 64 px.",
 "boss_lurker_queen": "The LURKER QUEEN facing right, larger than any lurker: a huge pallid eyeless matriarch in BONE and MIST washes with DUSK shadow, a blank brow, a wide needle-toothed maw, a tall CROWN of bone spines, FOUR long thin arms reaching down and out, a swollen belly, three small lurker hatchlings clinging to her flanks. TAG: BOSS — crowned, eyeless, many long arms. Reads at 64 px.",
 "boss_mirror_king": "The MIRROR KING facing right, larger than the warden: a tall regal figure whose whole body is a DARK MIRROR (flat INK/UMBRA with bright MIST edge light), a long DUSK robe with GILT trim, a tall spiked GILT CROWN, a tall sceptre topped with a round polished hand-mirror (a BONE disc), a pale crack across the featureless face. TAG: BOSS — crowned, mirror sceptre: the hero's dark reflection made king. Reads at 64 px.",
}
DEAD_WHO = {
 "boss_goblin_warlord": "the GOBLIN WARLORD (a towering gaunt goblin king, cold DUSK-green skin, a spiked iron crown, a tattered BLOOD-and-INK mantle, a huge cleaver)",
 "boss_bloat_mother": "the BLOAT MOTHER (a huge sac of pale teal-green gas, a crown of BONE spines, budding bloat-buds) — collapsed and deflated, sagging flat",
 "boss_lich": "the LICH (a gaunt skeleton king in INK-and-DUSK robes, a BONE skull-crown, a skull-topped staff, the cold flame guttered out)",
 "boss_foundry_master": "the FOUNDRY MASTER (a colossal riveted iron forge-lord, anvil chest, leather apron, spiked iron crown, a giant hammer; the EMBER seams cooling to CLOT)",
 "boss_lurker_queen": "the LURKER QUEEN (a huge pallid eyeless matriarch, bone-spine crown, four long thin arms)",
 "boss_mirror_king": "the MIRROR KING (a tall figure of dark mirror with MIST edge light, a spiked GILT crown, a mirror sceptre) — the mirror body cracked across",
}
for k, who in DEAD_WHO.items():
    B[f"{k}_dead"] = DEAD.format(who=who)


def main() -> None:
    p = Path(__file__).resolve().parent / "manifest.json"
    m = json.loads(p.read_text())
    n = 0
    for a in m["assets"]:
        if a["id"] in B:
            a["brief3"] = B[a["id"]]; n += 1
    p.write_text(json.dumps(m, indent=2, ensure_ascii=False) + "\n")
    print(f"brief3: {n} foes")


if __name__ == "__main__":
    main()
