import {execFileSync} from 'node:child_process';import {launchBrowser} from '../../tools/browser.mjs';import assert from 'node:assert/strict';import {mkdirSync} from 'node:fs';
const url=execFileSync('bash',['tools/dev.sh'],{cwd:new URL('../../',import.meta.url),encoding:'utf8'}).trim(),shots=process.env.RIDDLE_SHOTS;if(shots)mkdirSync(shots,{recursive:true});const b=await launchBrowser();
try{for(const width of [320,400,1440]){const p=await b.newPage({viewport:{width,height:900},deviceScaleFactor:1.5});await p.goto(`${url}?fresh=1&seed=1&runs=0`);await p.waitForFunction(()=>window.__riddle?.booted);await p.locator('.town-tag[data-next="house"]').waitFor({state:'visible'});await p.waitForFunction(()=>document.querySelector(".town-foundation").classList.contains("painted"));await p.waitForTimeout(400);
const before=await p.evaluate(()=>{const a=window.__riddle,t=document.querySelector('.town-tag'),f=document.querySelector('.town-foundation'),r=t.getBoundingClientRect(),fr=f.getBoundingClientRect(),s=getComputedStyle(t);return{kind:a.kind,home:a.lineage.town.home,heroes:a.lineage.hero_slots.length,foundation:!f.hidden,painted:f.classList.contains("painted"),plotW:fr.width,plotH:fr.height,separate:fr.bottom<=r.top||r.bottom<=fr.top,hitW:document.querySelector(".hit-staked").getBoundingClientRect().width,hitH:document.querySelector(".hit-staked").getBoundingClientRect().height,text:t.textContent.replace(/\s+/g,' '),h:r.height,w:r.width,inside:r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight,plotInside:fr.left>=0&&fr.right<=innerWidth&&fr.top>=0&&fr.bottom<=innerHeight,border:s.borderImageSource,overflow:document.documentElement.scrollWidth>innerWidth};});
assert.equal(before.kind,'wasm');assert.equal(before.home,false);assert.equal(before.heroes,0);assert.equal(before.foundation,true);assert.equal(before.painted,true);assert.equal(before.plotW,164);assert.equal(before.plotH,108);assert.equal(before.separate,true);assert.equal(before.hitW,164);assert.equal(before.hitH,108);assert.match(before.text,/Build houseFree/);assert.ok(before.h>=44&&before.w>=44&&before.inside&&before.plotInside);assert.notEqual(before.border,'none');assert.equal(before.overflow,false);
if(shots){await p.mouse.move(2,2);await p.screenshot({path:`${shots}/${width}-empty.png`});}
await p.evaluate(()=>{const a=window.__riddle,fn=a.engine.buildTown;window.buildCalls=0;let release;window.releaseBuild=()=>release();a.engine.buildTown=async id=>{window.buildCalls++;await new Promise(r=>release=r);return fn(id);};});
await p.locator('.town-tag[data-next="house"]').focus();await p.keyboard.press('Space');await p.keyboard.press('Space');await p.locator('.town-tag[data-next="house"]').click();await p.locator('.hit-staked').click();assert.equal(await p.evaluate(()=>window.buildCalls),1);assert.equal(await p.locator('.town-tag').getAttribute('aria-busy'),'true');assert.equal(await p.evaluate(()=>window.__riddle.lineage.town.home),false);
await p.evaluate(()=>window.releaseBuild());await p.waitForFunction(()=>window.__riddle.lineage.town.home===true);await p.waitForFunction(()=>document.querySelector('.town-foundation')?.hidden);await p.waitForFunction(()=>window.__riddle.lineage.hero_slots.length===1);await p.waitForFunction(()=>!document.querySelector('button.send')?.disabled);assert.equal(await p.evaluate(()=>window.buildCalls),1);
if(shots){await p.mouse.move(2,2);await p.screenshot({path:`${shots}/${width}-home.png`});}
console.log(width,'first plot visibility, controls, busy dedup and real construction PASS');await p.close();}}finally{await b.close();}
