import {execFileSync} from 'node:child_process';
import {launchBrowser} from '../../tools/browser.mjs';
const url=execFileSync('bash',['tools/dev.sh'],{cwd:new URL('../../',import.meta.url),encoding:'utf8'}).trim(),b=await launchBrowser();
try{for(const width of [400,1440]){
 const p=await b.newPage({viewport:{width,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(`${url}?engine=fake&fresh=1&runs=0`);await p.waitForFunction(()=>window.__riddle?.booted);
 const n=await p.evaluate(async()=>{
  const a=window.__riddle,{mergeReports}=await import('/src/app.ts');let n=0;const check=(ok,msg)=>{if(!ok)throw Error(msg);n++;};
  const base={elapsed_s:28800,runs:12,sampled:false,learned:[],bests:[],found:[],deaths:[{cause:'gas',n:12}],pending:[],marks_earned:0,tamed:[],hatched:[],lost:[],reel:[],salvaged:[],xp:{class:'fighter',gained:0,level_ups:0},renown:{gained:0,rank:0,ranks_up:0},gold:{home:0},deepest:13};
  const slot=(id,name,bests)=>({id,name,runs:1,deepest:13,gold:0,packages:[],...(bests===undefined?{}:{bests})});
  const rows=()=>[...document.querySelectorAll('.report-boss-row')],text=()=>document.querySelector('.report-bosses')?.textContent??'';
  const show=r=>a.go({kind:'report',report:r,absence:true});
  a.lineage.walls=[{boss:'bloat_mother',title:'Mother',depth:13,slain:true,known:true,fact:'mother: fire'}];
  show(base);check(rows().length===0,'historical slain wall cannot invent a victory');
  show({...base,bests:['D13','home:D13','first kill: rat','trophy: first bones','boss:bloat_mother:counter=throw fire'],learned:['boss:bloat_mother:counter=throw fire']});
  check(rows().length===0,'ordinary records and counter facts are not boss defeats');
  const win={...base,bests:['boss: bloat_mother','boss:bloat_mother']};show(win);
  check(rows().length===1,'duplicate explicit first kill shown once');
  check(text().includes('Boss defeated')&&text().includes('Bloat Mother'),'plain boss victory and readable name');
  check(!rows()[0].closest('.report-details'),'victory outside details');
  check(document.querySelector('.report-details').hidden,'details remain folded');
  check(document.querySelector('.report-details').textContent.includes('Bloat Mother defeated'),'expanded bests use readable victory name');
  check(!rows()[0].dataset.bloodline,'legacy single report has no invented owner');
  check(document.querySelector('[data-k="gold"]').textContent.includes('$0'),'zero actual gold remains unchanged');
  check(document.documentElement.scrollWidth<=innerWidth,'single victory fits viewport');
  const image=rows()[0].querySelector('img');await image.decode();check(image.naturalWidth>0&&image.getBoundingClientRect().width===44,'existing artwork decodes at44px');
  const multi={...win,bloodlines:[slot(2,'Thorn',['boss: bloat_mother']),slot(1,'Ash',['boss: goblin_warlord','boss: goblin_warlord'])]};show(multi);
  check(rows().length===2&&rows()[0].dataset.bloodline==='1','reported owners sort by slot id');
  check(rows()[0].textContent.includes('Ash')&&rows()[0].textContent.includes('Goblin Warlord'),'first owner retains its boss');
  check(rows()[1].textContent.includes('Thorn')&&rows()[1].textContent.includes('Bloat Mother'),'unselected owner retains its boss');
  const before=text();a.lineage.selected_bloodline=2;a.lineage.walls=[];a.emitLive();check(text()===before,'live selection and walls cannot rewrite historical victory');
  show({...multi,bloodlines:[slot(1,'Ash',[]),slot(2,'Thorn',['boss: bloat_mother'])]});
  check(rows().length===1&&rows()[0].dataset.bloodline==='2','waiting selected hero does not hide other victory');
  show({...multi,bloodlines:[slot(1,'Ash',['boss: bloat_mother']),slot(2,'Thorn',['boss: bloat_mother'])]});
  check(rows().length===2,'two owners may each earn the same first kill');
  check(document.documentElement.scrollWidth<=innerWidth,'multihero victories fit viewport');
  show({...win,bloodlines:[slot(1,'Ash',[]),slot(2,'Thorn',[])]});check(rows().length===0,'known empty summaries suppress top-level fallback');
  show({...win,bloodlines:[slot(1,'Old',undefined),slot(2,'Other',undefined)]});
  check(rows().length===1&&!rows()[0].dataset.bloodline&&!text().includes('Old'),'old multihero report has explicit unowned fallback');
  const next={...base,bloodlines:[slot(1,'Ash',['boss: lich','boss: goblin_warlord']),slot(2,'Thorn',[])]};
  const merged=mergeReports(multi,next);
  check(JSON.stringify(merged.bloodlines.find(s=>s.id===1).bests)===JSON.stringify(['boss: goblin_warlord','boss: lich']),'slice merge unions each owner records');
  check(merged.bloodlines.find(s=>s.id===2).bests.includes('boss: bloat_mother'),'later empty slice preserves earned victory');
  check(multi.bloodlines[0].bests.length===1,'merge does not mutate prior report');
  show(merged);check(rows().length===3,'merged owner victories all render');
  const old=mergeReports({...base,bloodlines:[slot(1,'Old',undefined)]},{...base,bloodlines:[slot(1,'Old',undefined)]});
  check(old.bloodlines[0].bests===undefined,'unknown old fields stay unknown');
  show({...base,bests:['boss: ancient_clockwork']});check(text().includes('Ancient Clockwork')&&rows()[0].querySelector('.unit-icon[data-glyph="?"]'),'unknown explicit boss has readable fallback icon');
  show(base);check(rows().length===0,'later empty report does not repeat old victory');
  return n;
 });if(errors.length)throw Error(errors.join('\n'));console.log(width,n,'boss victories/ownership/slice merge/old wire checks PASS');await p.close();
}}finally{await b.close();}
