// Derive the dev bridge from shipping bindings, rather than duplicating game calls.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export function generate(source) {
  const methods = [], arms = [], extracted = [];
  const re = /pub fn (\w+)\(([^)]*)\)(?:\s*->\s*([^\n{]+))?\s*\{/g;
  let prior = 0;
  for (const match of source.matchAll(re)) {
    const prefix = source.slice(prior, match.index);
    prior = match.index + match[0].length;
    const [, rust, params, rawReturn] = match;
    extracted.push(rust);
    if (["new", "from_save", "version"].includes(rust)) continue;
    const alias = [...prefix.matchAll(/#\[wasm_bindgen\(js_name\s*=\s*(\w+)\)\]/g)].at(-1)?.[1] ?? rust;
    const args = params.split(",").map((p) => p.trim()).filter((p) => p && !/^&(?:mut )?self$/.test(p)).map((p) => {
      const m = /^(\w+):\s*(&str|u32|i32|f64|bool|Option<bool>)$/.exec(p);
      if (!m) throw new Error(`unsupported native parameter: ${rust} ${p}`);
      return { name: m[1], type: m[2] };
    });
    const returns = (rawReturn ?? "()").replace(/\s/g, "");
    if (!["String", "()", "Result<String,JsError>", "Result<(),JsError>"].includes(returns)) throw new Error(`unsupported native return: ${rust} ${returns}`);
    const call = `g.${rust}(${args.map((_, i) => `arg(args, ${i})?`).join(", ")})${returns.startsWith("Result") ? ".map_err(|e| e.to_string())?" : ""}`;
    const voidResult = returns.includes("()");
    arms.push(`        "${alias}" => { ${voidResult ? `${call}; Ok(Value::Null)` : `Ok(Value::String(${call}))`} },`);
    methods.push({ name: alias, args, void: voidResult, raw: ["save", "exportRules"].includes(alias) });
  }
  const declared = [...source.matchAll(/\bpub fn\s+(\w+)\s*\(/g)].map(m => m[1]);
  if (JSON.stringify(declared) !== JSON.stringify(extracted)) throw new Error('unsupported native function signature');
  if (new Set(methods.map(m => m.name)).size !== methods.length) throw new Error('duplicate native method alias');
  if (methods.length < 60 || !methods.some((m) => m.name === "advance")) throw new Error("shipping bridge extraction incomplete");
  const hash = createHash("sha256").update(source).digest("hex");
  const bridge = source.replace(/^\/\/!.*\n/gm, "").replace(/^\s*#\[wasm_bindgen(?:\([^\n]*\))?\]\s*\n/gm, "").replace("use wasm_bindgen::prelude::*;", `#[derive(Debug)]\npub struct JsError(String);\nimpl JsError { pub fn new(s: &str) -> Self { Self(s.into()) } }\nimpl std::fmt::Display for JsError { fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str(&self.0) } }`);
  if (/wasm_bindgen/.test(bridge)) throw new Error("unhandled wasm attribute");
  const rust = `// Generated by tools/native-codegen.mjs; shipping bridge SHA256 ${hash}\n#[allow(dead_code)]\nmod bridge {\n${bridge}\n}\nuse serde_json::Value;\nfn arg<'a, T: serde::Deserialize<'a>>(args: &'a [Value], i: usize) -> Result<T, String> {\n    T::deserialize(args.get(i).unwrap_or(&Value::Null)).map_err(|e| format!("argument {i}: {e}"))\n}\npub fn new_game() -> bridge::Game { bridge::Game::new(0) }\npub fn dispatch(g: &mut bridge::Game, method: &str, args: &[Value]) -> Result<Value, String> {\n    match method {\n        "version" => Ok(Value::String(bridge::version())),\n        "__bridge" => Ok(Value::String("${hash}".into())),\n${arms.join("\n")}\n        "__validateBalance" => { riddle_core::balance::parse(arg(args, 0)?).map(|_| Value::Null) },\n        "__balance" => Ok(Value::String(serde_json::to_string(riddle_core::balance::get()).unwrap())),\n        _ => Err(format!("unknown engine method {method}")),\n    }\n}\n`;
  return { rust, metadata: JSON.stringify({ bridgeSha256: hash, methods }) + "\n" };
}
export function writeGenerated(check = false) {
  const result = generate(readFileSync(resolve(ROOT, "crates/riddle-wasm/src/lib.rs"), "utf8"));
  for (const [path, body] of [["crates/riddle-core/examples/native_dev/generated.rs", result.rust], ["web/src/engine/native-api.json", result.metadata]]) {
    const file = resolve(ROOT, path);
    if (existsSync(file) && readFileSync(file, "utf8") === body) continue;
    if (check) throw new Error(`stale native bridge: ${path}; run node tools/native-codegen.mjs`);
    mkdirSync(dirname(file), { recursive: true }); writeFileSync(file, body);
  }
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) writeGenerated(process.argv.includes("--check"));
