#!/usr/bin/env python3
"""Cut 17: pack the UI skin for the client.

art/ui/frames/*.png (14 frames), art/ui/icons/*.png (22 icons) and art/ui/portraits/*.png (headshots), generated by Codex, are downscaled to the
client's 2x density into web/public/ui/{frames,icons}/, and web/src/ui/skin.json lists what is present — the
client references only listed files (a missing PNG must never 404: art never blocks the game, and the client
gates fail on console errors). Re-run whenever art lands:

    python3 tools/ui-skin.py

9-slice frames keep their insets proportional: the scaled inset is written to skin.json (`slice`), and the CSS
uses it as `border-image-slice` with a CSS border width of slice / 2 (2x density).
"""
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC_F, SRC_I, SRC_P, SRC_B, SRC_D = ROOT / "art/ui/frames", ROOT / "art/ui/icons", ROOT / "art/ui/portraits", ROOT / "art/ui/backdrops", ROOT / "art/ui/deco"
OUT = ROOT / "web/public/ui"
MANIFEST = ROOT / "web/src/ui/skin.json"

# name: (scale, source 9-slice inset or None)
FRAMES = {
    "bar": (0.5, 40), "console": (0.5, 96), "panel": (0.5, 56), "tablet": (0.5, 48), "tablet_card": (0.5, 48),
    "tile": (0.5, 48), "tile_pressed": (0.5, 48), "well": (0.5, None), "gem": (0.5, None), "gem_red": (0.5, None),
    "banner": (0.5, None), "gauge": (0.5, 16), "stud": (1.0, None), "seal": (0.5, None),
    "button": (0.5, None),   # gfx round 24: the carved primary button (the WHY sheet's EDIT): a 9-slice the CSS slices itself
    "plaque_minimap": (0.5, 64), "plaque_roster": (0.5, 64),   # art direction phase 2: the town's minimap and roster plaques (docs/TOWN.md §5)
    "scroll": (0.5, None),   # gfx round 8: the report's hanging scroll (9-slice top/bottom 160, sides 72 at source: the CSS writes its own slice)
}
ICON_PX = 96   # 48 CSS px at 2x
BACKDROP_W = 720   # gfx round 1: painted backdrops behind a place (death, report), 1024×1536 opaque portraits from Codex
PORTRAIT_PX = 256   # art pass: the well's face is 56 CSS px (168 device px at 3x); square, opaque — the CSS circle masks it


def usable(im: Image.Image) -> bool:
    """RGBA with transparent corners (a frame or icon painted on a fill is unusable)."""
    if im.mode != "RGBA":
        return False
    w, h = im.size
    return all(im.getpixel(p)[3] < 16 for p in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)])


def main() -> None:
    (OUT / "frames").mkdir(parents=True, exist_ok=True)
    (OUT / "icons").mkdir(parents=True, exist_ok=True)
    frames, icons, bad = {}, [], []
    for name, (scale, inset) in FRAMES.items():
        p = SRC_F / f"{name}.png"
        if not p.exists():
            continue
        im = Image.open(p).convert("RGBA") if Image.open(p).mode != "RGBA" else Image.open(p)
        if not usable(im):
            bad.append(str(p.relative_to(ROOT)))
            continue
        w, h = round(im.width * scale), round(im.height * scale)
        im.resize((w, h), Image.LANCZOS).save(OUT / "frames" / f"{name}.png", optimize=True)
        frames[name] = {"w": w, "h": h, **({"slice": round(inset * scale)} if inset else {})}
    for p in sorted(SRC_I.glob("*.png")):
        im = Image.open(p)
        im = im.convert("RGBA") if im.mode != "RGBA" else im
        if not usable(im):
            bad.append(str(p.relative_to(ROOT)))
            continue
        im.resize((ICON_PX, ICON_PX), Image.LANCZOS).save(OUT / "icons" / p.name, optimize=True)
        icons.append(p.stem)
    # art pass: headshot portraits (hero_<class>, pet_<kind>, captive, boss_<kind>), 1024 opaque squares from Codex
    (OUT / "portraits").mkdir(parents=True, exist_ok=True)
    portraits = []
    for p in sorted(SRC_P.glob("*.png")) if SRC_P.exists() else []:
        im = Image.open(p).convert("RGB")
        if im.width != im.height or im.width < 512:
            bad.append(str(p.relative_to(ROOT)))
            continue
        im.resize((PORTRAIT_PX, PORTRAIT_PX), Image.LANCZOS).save(OUT / "portraits" / f"{p.stem}.webp", quality=88, method=6)
        portraits.append(p.stem)
    (OUT / "backdrops").mkdir(parents=True, exist_ok=True)
    backdrops = []
    for p in sorted(SRC_B.glob("*.png")) if SRC_B.exists() else []:
        im = Image.open(p).convert("RGB")
        if im.height < im.width or im.width < 512:
            bad.append(str(p.relative_to(ROOT)))
            continue
        im.resize((BACKDROP_W, round(im.height * BACKDROP_W / im.width)), Image.LANCZOS).save(OUT / "backdrops" / f"{p.stem}.webp", quality=82, method=6)
        backdrops.append(p.stem)
    # gfx round 4: decoration (the desktop columns' carved pillar, the camp's braziers): half size, alpha kept where it has one
    (OUT / "deco").mkdir(parents=True, exist_ok=True)
    deco = []
    for p in sorted(SRC_D.glob("*.png")) if SRC_D.exists() else []:
        im = Image.open(p)
        im = im.convert("RGBA") if im.mode in ("RGBA", "LA", "P") else im.convert("RGB")
        if im.mode == "RGBA" and not usable(im):
            bad.append(str(p.relative_to(ROOT)))
            continue
        im.resize((im.width * 3 // 4, im.height * 3 // 4), Image.LANCZOS).save(OUT / "deco" / f"{p.stem}.webp", quality=84, method=6)
        deco.append(p.stem)
    # gfx round 10: effect art (the boss's shield and its shards, art/ui/fx): 256 px on its long side, alpha kept
    (OUT / "fx").mkdir(parents=True, exist_ok=True)
    fx = []
    for p in sorted((ROOT / "art/ui/fx").glob("*.png")) if (ROOT / "art/ui/fx").exists() else []:
        im = Image.open(p).convert("RGBA")
        if not usable(im):
            bad.append(str(p.relative_to(ROOT)))
            continue
        sc = 256 / max(im.size)
        im.resize((round(im.width * sc), round(im.height * sc)), Image.LANCZOS).save(OUT / "fx" / f"{p.stem}.webp", quality=88, method=6)
        fx.append(p.stem)
        # gfx round 21 (raters: "the painted shield clashes with the pixel sprites"): the same art cut to the sprites' pixel register — a box
        # downscale (the shield 28 px, a shard 12 px), <= 16 colours, a hard alpha and a 1-px dark outline; drawn `pixelated` 3x in the view
        px = 32 if p.stem == "shield" else 14
        s2 = px / max(im.size)
        small = im.resize((max(1, round(im.width * s2)), max(1, round(im.height * s2))), Image.BOX)
        a = small.getchannel("A").point(lambda v: 255 if v >= 110 else 0)
        from PIL import ImageEnhance
        rgb = ImageEnhance.Contrast(ImageEnhance.Brightness(small.convert("RGB")).enhance(1.35)).enhance(1.4)   # (a box average goes muddy at 28 px)
        rgb = rgb.quantize(16, method=Image.Quantize.MEDIANCUT).convert("RGB")
        pix = Image.new("RGBA", small.size, (0, 0, 0, 0))
        pix.paste(rgb, (0, 0), a)
        edge = Image.new("RGBA", (small.width + 2, small.height + 2), (0, 0, 0, 0))
        for dx, dy in ((0, 1), (2, 1), (1, 0), (1, 2)):
            edge.paste((16, 10, 8, 255), (dx, dy), a)
        edge.alpha_composite(pix, (1, 1))
        edge.save(OUT / "fx" / f"{p.stem}_px.png")
        fx.append(f"{p.stem}_px")
    # Cut 30 §5: the quest board's reward pictures (art/ui/oath/: card, heir, route, row, slot, title, verb, waystone), 256 px opaque
    (OUT / "quest").mkdir(parents=True, exist_ok=True)
    quest = []
    for p in sorted((ROOT / "art/ui/oath").glob("*.png")) if (ROOT / "art/ui/oath").exists() else []:
        Image.open(p).convert("RGB").resize((256, 256), Image.LANCZOS).save(OUT / "quest" / f"{p.stem}.webp", quality=86, method=6)
        quest.append(p.stem)
    # keys other tools own (tools/foe-portraits.py `foes`) are kept
    old = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
    old.update({"frames": frames, "icons": icons, "portraits": portraits, "backdrops": backdrops, "deco": deco, "fx": fx, "quest": quest})
    MANIFEST.write_text(json.dumps(old, indent=1) + "\n")
    print(f"ui-skin: {len(frames)} frames, {len(icons)} icons, {len(portraits)} portraits, {len(backdrops)} backdrops, {len(deco)} deco, {len(fx)} fx -> web/public/ui/" + (f"; unusable: {', '.join(bad)}" if bad else ""))


if __name__ == "__main__":
    main()
