#!/usr/bin/env python3
"""Cut 17: pack the UI skin for the client.

art/ui/frames/*.png (14 frames) and art/ui/icons/*.png (22 icons), generated by Codex, are downscaled to the
client's 2x density into web/public/ui/{frames,icons}/, and web/src/ui/skin.json lists what is present — the
client references only listed files (a missing PNG must never 404: art never blocks the game, and the client
gates fail on console errors). Re-run whenever art lands:

    python3 tools/ui-skin.py

9-slice frames keep their insets proportional: the scaled inset is written to skin.json (`slice`), and the CSS
uses it as `border-image-slice` with a CSS border width of slice / 2 (2x density).
"""
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC_F, SRC_I = ROOT / "art/ui/frames", ROOT / "art/ui/icons"
OUT = ROOT / "web/public/ui"
MANIFEST = ROOT / "web/src/ui/skin.json"

# name: (scale, source 9-slice inset or None)
FRAMES = {
    "bar": (0.5, 40), "console": (0.5, 96), "panel": (0.5, 56), "tablet": (0.5, 48), "tablet_card": (0.5, 48),
    "tile": (0.5, 48), "tile_pressed": (0.5, 48), "well": (0.5, None), "gem": (0.5, None), "gem_red": (0.5, None),
    "banner": (0.5, None), "gauge": (0.5, 16), "stud": (1.0, None), "seal": (0.5, None),
}
ICON_PX = 96   # 48 CSS px at 2x


def usable(im: Image.Image) -> bool:
    """RGBA with transparent corners (a frame or icon painted on a fill is unusable)."""
    if im.mode != "RGBA":
        return False
    w, h = im.size
    return all(im.getpixel(p)[3] < 16 for p in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)])


def main() -> None:
    (OUT / "frames").mkdir(parents=True, exist_ok=True)
    (OUT / "icons").mkdir(parents=True, exist_ok=True)
    frames, icons, bad = {}, [], []
    for name, (scale, inset) in FRAMES.items():
        p = SRC_F / f"{name}.png"
        if not p.exists():
            continue
        im = Image.open(p).convert("RGBA") if Image.open(p).mode != "RGBA" else Image.open(p)
        if not usable(im):
            bad.append(str(p.relative_to(ROOT)))
            continue
        w, h = round(im.width * scale), round(im.height * scale)
        im.resize((w, h), Image.LANCZOS).save(OUT / "frames" / f"{name}.png", optimize=True)
        frames[name] = {"w": w, "h": h, **({"slice": round(inset * scale)} if inset else {})}
    for p in sorted(SRC_I.glob("*.png")):
        im = Image.open(p)
        im = im.convert("RGBA") if im.mode != "RGBA" else im
        if not usable(im):
            bad.append(str(p.relative_to(ROOT)))
            continue
        im.resize((ICON_PX, ICON_PX), Image.LANCZOS).save(OUT / "icons" / p.name, optimize=True)
        icons.append(p.stem)
    MANIFEST.write_text(json.dumps({"frames": frames, "icons": icons}, indent=1) + "\n")
    print(f"ui-skin: {len(frames)} frames, {len(icons)} icons -> web/public/ui/" + (f"; unusable: {', '.join(bad)}" if bad else ""))


if __name__ == "__main__":
    main()
