// Generated by tools/native-codegen.mjs; shipping bridge SHA256 3f8f0a0b36136ab76109e489cfce56472995bb8dd28eaf3df1b2efb763c25724
#[allow(dead_code)]
mod bridge {
use riddle_core::bloodlines::Session as Core;
#[derive(Debug)]
pub struct JsError(String);
impl JsError { pub fn new(s: &str) -> Self { Self(s.into()) } }
impl std::fmt::Display for JsError { fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str(&self.0) } }
pub fn version() -> String {
    "0.1.0".into()
}

fn js<T: serde::Serialize>(v: &T) -> String {
    serde_json::to_string(v).unwrap_or_else(|_| "null".into())
}

fn err(e: String) -> JsError {
    JsError::new(&e)
}

fn ids(text: &str) -> Result<Vec<u32>, JsError> {
    serde_json::from_str::<Vec<u32>>(text).map_err(|e| err(e.to_string()))
}
pub struct Game {
    inner: Core,
}
impl Game {
    pub fn new(seed: u32) -> Game {
        Game { inner: Core::new(seed as u64) }
    }

    /// Start a fresh lineage in place; returns the Lineage.
    pub fn new_lineage(&mut self, seed: u32) -> String {
        self.inner = Core::new(seed as u64);
        js(&self.inner.lineage())
    }

    /// Replace the state from a save; returns the Lineage.
    pub fn load(&mut self, save: &str) -> Result<String, JsError> {
        self.inner = Core::load(save).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// A new Game from a save (static).
    pub fn from_save(save: &str) -> Result<Game, JsError> {
        Ok(Game { inner: Core::load(save).map_err(err)? })
    }

    pub fn save(&self) -> String {
        self.inner.save()
    }

    pub fn vocabulary(&self) -> String {
        js(&self.inner.vocabulary_wire())
    }
    pub fn set_rules(&mut self, set: &str) -> Result<(), JsError> {
        let set = riddle_core::RuleSet::parse(set).map_err(err)?;
        self.inner.set_rules(set).map_err(err)
    }

    /// `itemIds`: JSON array of vault item ids to bring.
    pub fn loadout(&mut self, item_ids: &str) -> Result<(), JsError> {
        let v = ids(item_ids)?;
        self.inner.loadout(v);
        Ok(())
    }

    pub fn forecast(&self) -> String {
        js(&self.inner.forecast())
    }

    /// Cut 6 §9: the same forecast at 100 sims (same seeds first), the client's refine pass.
    pub fn forecast_refine(&self) -> String {
        js(&self.inner.forecast_refine())
    }

    pub fn send(&mut self) -> Result<String, JsError> {
        self.inner.try_send().map(|s| js(&s)).map_err(err)
    }

    pub fn step(&mut self, turns: u32) -> String {
        js(&self.inner.step(turns))
    }
    pub fn run_offline(&mut self, elapsed_s: f64) -> String {
        js(&self.inner.run_offline(elapsed_s.max(0.0) as u64))
    }

    /// Offline batch without the worst-death verdict (report carries `worst_death_id`).
    pub fn run_offline_quick(&mut self, elapsed_s: f64) -> String {
        js(&self.inner.run_offline_mode(elapsed_s.max(0.0) as u64, false, true))
    }

    /// One slice of a chunked absence (`runOfflineQuick`); a slice before the `last` carries no
    /// stall verdict (the client reads the last slice's: its patch forecasts were most of an
    /// absence's time on a plateaued lineage — 3 of the D11 fixture's 16 slices paid ~2 s each).
    pub fn run_offline_slice(&mut self, elapsed_s: f64, last: bool) -> String {
        let secs = elapsed_s.max(0.0) as u64;
        js(&self.inner.run_offline_mode(secs, false, last))
    }

    pub fn death(&mut self, run_id: u32) -> Result<String, JsError> {
        self.inner.death(run_id).map(|d| js(&d)).ok_or_else(|| err(format!("no death record for run {run_id}")))
    }

    /// QA on 23ed91f: the death's shown patches with the camp's own reach deltas (seconds:
    /// four camp panels); `death` answers first with them `camp_pending`.
    pub fn death_deltas(&mut self, run_id: u32) -> Result<String, JsError> {
        self.inner.death_deltas(run_id).map(|d| js(&d)).ok_or_else(|| err(format!("no death record for run {run_id}")))
    }

    pub fn buy(&mut self, unlock: &str) -> Result<String, JsError> {
        self.inner.buy(unlock).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 15 §2: buy with gold at `UnlockInfo.gold` (marks untouched); returns the lineage.
    pub fn buy_unlock_gold(&mut self, unlock: &str) -> Result<String, JsError> {
        self.inner.buy_unlock_gold(unlock).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    pub fn lineage(&self) -> String {
        js(&self.inner.lineage())
    }
    pub fn export_rules(&self) -> String {
        self.inner.export_rules()
    }
    pub fn import_rules(&self, text: &str) -> Result<String, JsError> {
        self.inner.import_rules(text).map(|r| js(&r)).map_err(err)
    }

    // ---- additions (see README): unlock catalogue, class, saved sets

    pub fn unlocks(&self) -> String {
        js(&self.inner.unlocks())
    }

    /// Cut 4 §9: the catalogue with `delta` simulated for every open card and verb (memoised
    /// per lineage state; `unlocks()` carries the same deltas afterwards without sims).
    pub fn unlock_deltas(&self) -> String {
        js(&self.inner.unlock_deltas())
    }
    pub fn set_class(&mut self, class: &str) -> Result<String, JsError> {
        self.inner.set_class(class).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }
    pub fn select_set(&mut self, index: u32) -> String {
        self.inner.select_set(index as usize);
        js(&self.inner.lineage())
    }

    /// Cut 13 §2: pick the new heir's trait from `Lineage.trait_offer` (before the first
    /// send; a send without a pick keeps the first); returns the Lineage.
    pub fn set_trait(&mut self, name: &str) -> Result<String, JsError> {
        self.inner.set_trait(name).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    // ---- Addendum A: companions
    pub fn set_party(&mut self, ids_json: &str) -> Result<String, JsError> {
        let v = ids(ids_json)?;
        self.inner.set_party(v).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }
    pub fn set_companion_rules(&mut self, id: u32, set: &str) -> Result<(), JsError> {
        let set = riddle_core::RuleSet::parse(set).map_err(err)?;
        self.inner.set_companion_rules(id, set).map_err(err)
    }

    pub fn breed(&mut self, a: u32, b: u32) -> Result<String, JsError> {
        self.inner.breed(a, b).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    pub fn hatch(&mut self, egg_id: u32) -> Result<String, JsError> {
        self.inner.hatch(egg_id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }
    pub fn companion_vocabulary(&self, id: u32) -> Result<String, JsError> {
        self.inner.companion_vocabulary(id).map(|v| js(&v)).map_err(err)
    }

    // ---- Addendum B: gold and supplies
    pub fn buy_supply(&mut self, kind: &str) -> Result<String, JsError> {
        self.inner.buy_supply(kind).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }
    pub fn drop_supply(&mut self, id: u32) -> Result<String, JsError> {
        self.inner.drop_supply(id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }
    pub fn clear_supplies(&mut self) -> String {
        self.inner.clear_supplies();
        js(&self.inner.lineage())
    }
    pub fn supply_catalogue(&self) -> String {
        js(&self.inner.supply_catalogue())
    }

    // ---- Addendum D: vault keep at exit

    /// `ids`: JSON array of item ids from `StepResult.exit_pending.items` to vault.
    /// QA on 23ed91f: resolve the pending exit by the keep preference and owned automations
    /// (`ExitPending.auto_keep`, replacing a weaker vault item of the same category when the
    /// vault is full) — the skipped keep sheet's call (`keep([])` keeps nothing).
    pub fn auto_keep(&mut self) -> String {
        self.inner.auto_keep();
        js(&self.inner.lineage())
    }

    pub fn keep(&mut self, ids_json: &str) -> Result<String, JsError> {
        let v = ids(ids_json)?;
        self.inner.keep(v).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// QA on 308f045: take an item out of the vault — salvaged at a bank's share (the lineage).
    pub fn sell_vault(&mut self, id: u32) -> Result<String, JsError> {
        self.inner.sell_vault(id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Insure a vault item against loss on death (25% of salvage value ×10).
    pub fn insure(&mut self, id: u32) -> Result<String, JsError> {
        self.inner.insure(id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }
    pub fn set_keep_pref(&mut self, pref: &str) -> Result<String, JsError> {
        self.inner.set_keep_pref(pref).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Hero looks: the heirs' cosmetic look (`male | female | cat`); returns the Lineage.
    pub fn set_look(&mut self, look: &str) -> Result<String, JsError> {
        self.inner.set_look(look).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    // ---- Cut 5: bail, the vault choice, the vault preference

    /// §5: queue a `return` for the hero's next action (the rules untouched).
    pub fn bail(&mut self) {
        self.inner.bail();
    }

    /// §4: take one item of the opened vault (`Snapshot.vault_choice.items[].id`); returns
    /// the Snapshot.
    pub fn choose(&mut self, item_id: u32) -> Result<String, JsError> {
        self.inner.choose(item_id).map_err(err)?;
        Ok(js(&self.inner.snapshot()))
    }

    /// §4: what an unwatched vault choice takes (`weapon | armour | potion | scroll`).
    pub fn set_vault_pref(&mut self, pref: &str) -> Result<String, JsError> {
        self.inner.set_vault_pref(pref).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    // ---- Cut 19

    /// §1: each cage preference measured for the active set — `CageOption[]` (`pref`,
    /// `current`, `depth`, `reach`/`reach_delta`, `bank`/`bank_delta`, `gold`/`gold_delta`,
    /// `delta` — the picker's headline — and `pm`). Four camp panels (three new): call it when
    /// the cage tablet's picker opens, or after the refine; memoised like the forecast.
    /// QA on 524827b: `refined` — measure on the camp's refined pass (the sheet's current option
    /// is then the camp's number); absent, the lineage's own read (`forecast::camp_sims`).
    pub fn cage_forecast(&self, refined: Option<bool>) -> String {
        match refined {
            Some(r) => js(&self.inner.cage_forecast_refined(r)),
            None => js(&self.inner.cage_forecast()),
        }
    }

    /// §3: the loadout's repeat on or off (off refunds the re-packed shelf); returns the Lineage.
    pub fn set_restock(&mut self, on: bool) -> String {
        self.inner.set_restock(on);
        js(&self.inner.lineage())
    }

    // ---- Cut 21

    /// §1: the floor the next sends start on — 1 or a lit waystone (`Lineage.waystones`);
    /// refused when not lit; returns the Lineage (`start`, `start_toll`).
    pub fn set_start(&mut self, depth: u32) -> Result<String, JsError> {
        self.inner.set_start(depth).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// §1: each start the tablet offers (D1 and every lit waystone) measured for the active
    /// set — `StartOption[]` (`depth`, `current`, `toll`, `short`, `bar`, `reach`/`reach_delta`,
    /// `bank`/`bank_delta`, `gold`, `net`/`net_delta`, `pm`). One camp panel per option (seconds
    /// in wasm): call it when the tablet opens, or after the refine; memoised like the forecast.
    pub fn start_forecast(&self, refined: Option<bool>) -> String {
        // QA on 308f045: `refined` — the camp's pass (the cage tablet's rule); absent, the camp's own
        match refined {
            Some(r) => js(&self.inner.start_forecast_refined(r)),
            None => js(&self.inner.start_forecast()),
        }
    }

    /// Cut 26 §2: the fork chip's option tablet — both stairs of the fork at `fork` (5, 9, 14, 19,
    /// 24) for the active set: `ForkOption[]` (`biome`, `far`, `current`, `route` — the set's
    /// route with that stair —, `depth` the band's last floor, `reach`/`reach_delta`, `bank`,
    /// `gold`, `death`, `delta`, `pm`). One camp panel (the other stair's); memoised. A route
    /// edit itself is `setRules` with the set's `route` (fork depths of its far stairs).
    pub fn fork_forecast(&self, fork: u32, refined: Option<bool>) -> String {
        // QA on 308f045: `refined` — the camp's pass (the cage tablet's rule); absent, the camp's own
        match refined {
            Some(r) => js(&self.inner.fork_forecast_refined(fork, r)),
            None => js(&self.inner.fork_forecast(fork)),
        }
    }

    /// Cut 22 §3: the edit's paired move — the active set's camp panel minus `prev`'s (JSON
    /// RuleSet: the set as it was at the last painted forecast) on the same seeds —
    /// `ForecastVs` (`depths[{depth, delta, pm, abs_pm}]`, `bank`/`death`/`return`/`gold` as
    /// `{delta, pm}`, `sims`). The active panel is the forecast's own (cached); the previous
    /// set's is usually cached from its paint. Call it after the forecast's first paint.
    pub fn forecast_vs(&self, prev: &str) -> Result<String, JsError> {
        let prev = riddle_core::RuleSet::parse(prev).map_err(err)?;
        Ok(js(&self.inner.forecast_vs(&prev)))
    }

    /// Cut 27 §1: right after `send` — play the floors the set clears ≥ 95 % and return the fold
    /// line (`FoldLine`: `from`, `to`, `clear`, `gold`, `beats`, `chips`, `floors[]` with each
    /// floor's snapshot and events, `step` as one `step()`). Nothing folded: `to < from`.
    pub fn fold(&mut self) -> String {
        js(&self.inner.fold())
    }

    /// Cut 27 §2: the edit as a scene against `prev` (JSON RuleSet: the sent set) — `Divergence`
    /// or `null` when the sets play alike on every seed tried. Reads the camp's paired panels
    /// (cached by the forecast and its `vs`); call it after the forecast's `vs`.
    pub fn divergence(&self, prev: &str) -> Result<String, JsError> {
        let prev = riddle_core::RuleSet::parse(prev).map_err(err)?;
        Ok(js(&self.inner.divergence(&prev)))
    }

    /// Cut 28 §2: the camp's move against `prev` (JSON RuleSet: the set sent), attributed to the
    /// state since the send and the rows (`ForecastMove`: `whole`, `parts[{kind, text, move}]`,
    /// `lead`, `rows`, `state`), or `null` when no send was recorded. 2–6 camp panels: call it on
    /// a background lane after the forecast.
    pub fn forecast_move(&self, prev: &str) -> Result<String, JsError> {
        let prev = riddle_core::RuleSet::parse(prev).map_err(err)?;
        Ok(js(&self.inner.forecast_move(&prev)))
    }

    /// Cut 28 §1: swear the standing oath `id` (pays its price); returns the Lineage.
    pub fn swear_oath(&mut self, id: &str) -> Result<String, JsError> {
        self.inner.swear_oath(id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 28 §1: forswear the sworn oath (half its price back); returns the Lineage.
    pub fn forswear_oath(&mut self) -> Result<String, JsError> {
        self.inner.forswear_oath().map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 29 §1: forswear the sworn oath `id` (either slot); returns the Lineage.
    pub fn forswear_oath_id(&mut self, id: &str) -> Result<String, JsError> {
        self.inner.forswear_oath_id(id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 29 §1: an oath draw (◆2): a fresh standing oath; returns the Lineage.
    pub fn draw_oath(&mut self) -> Result<String, JsError> {
        self.inner.draw_oath().map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 29 §5: commission the next work with gold; returns the Lineage.
    pub fn commission(&mut self) -> Result<String, JsError> {
        self.inner.commission().map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 29 §1 (E1): at a wall, the one-row edit that passes it (`WallEdit` JSON, or `null`) —
    /// searched once a day (seconds to minutes in wasm: call it on the report, off the foreground),
    /// the cached offer after (`Lineage.wall`).
    pub fn wall_edit(&mut self) -> String {
        js(&self.inner.wall_edit())
    }

    /// Cut 29 §2: the camp showed the newly opened systems (clears `Lineage.systems[].new`); returns the Lineage.
    pub fn seen_systems(&mut self) -> String {
        self.inner.seen_systems();
        js(&self.inner.lineage())
    }

    /// Cut 29 §4: set the standing orders (a `StandingOrders` JSON); returns the Lineage.
    pub fn set_orders(&mut self, orders_json: &str) -> Result<String, JsError> {
        let o: riddle_core::wire::StandingOrders = serde_json::from_str(orders_json).map_err(|e| JsError::new(&e.to_string()))?;
        self.inner.set_orders(&o).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    // ---- Cut 30: packages, drills, the bank, the quest board

    /// Cut 30 §2: equip a package (`id`: a stance, a tactic in `slot` 0/1, a temperament); returns the Lineage.
    pub fn equip_package(&mut self, id: &str, slot: u32) -> Result<String, JsError> {
        self.inner.equip_package(id, slot as usize).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 30 §2: empty a tactic or temperament slot; returns the Lineage.
    pub fn unequip_package(&mut self, id: &str) -> Result<String, JsError> {
        self.inner.unequip_package(id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 30 §2: take a wake card (`Lineage.packages.offer`); returns the Lineage.
    pub fn pick_temperament(&mut self, id: &str) -> Result<String, JsError> {
        self.inner.pick_temperament(id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 30 §2: spend marks on a package's next level; returns the Lineage.
    pub fn spend_level(&mut self, id: &str) -> Result<String, JsError> {
        self.inner.spend_level(id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 30 §1: revoke (or restore) a drill — one tap; returns the Lineage.
    pub fn revoke_drill(&mut self, boss: &str, revoked: bool) -> Result<String, JsError> {
        self.inner.revoke_drill(boss, revoked).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 30 §2: every package move priced on the paired panel (`PkgOption[]`, best first).
    pub fn package_options(&self, sims: u32) -> String {
        js(&self.inner.package_options(sims.max(8)))
    }

    /// Cut 30 §3: deposit gold in the bank (capped); returns the Lineage.
    pub fn bank_deposit(&mut self, amount: i32) -> Result<String, JsError> {
        self.inner.bank_deposit(amount).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 30 §3: take gold out of the bank; returns the Lineage.
    pub fn bank_withdraw(&mut self, amount: i32) -> Result<String, JsError> {
        self.inner.bank_withdraw(amount).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 30 §5: the day's free swap of the quest on the board; returns the Lineage.
    pub fn swap_quest(&mut self) -> Result<String, JsError> {
        self.inner.swap_quest().map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 30.5: hire the lit node's worker; returns the Lineage.
    pub fn select_bloodline(&mut self, id:u32) -> Result<String, JsError> {
        self.inner.select_bloodline(id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }
    pub fn add_bloodline(&mut self) -> Result<String, JsError> {
        self.inner.add_bloodline().map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }
    pub fn upgrade_hero(&mut self, id: &str) -> Result<String, JsError> {
        self.inner.upgrade_hero(id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }
    pub fn build_town(&mut self, id: &str) -> Result<String, JsError> {
        self.inner.build_town(id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }
    pub fn hire(&mut self, id: &str) -> Result<String, JsError> {
        self.inner.hire(id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 30.5, week 2: promote the worker whose rank is on offer; returns the Lineage.
    pub fn promote(&mut self, id: &str) -> Result<String, JsError> {
        self.inner.promote(id).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 30.5: the haul chest into the purse; returns the Lineage.
    pub fn open_chest(&mut self) -> Result<String, JsError> {
        self.inner.open_chest().map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 30.5: switch a hired worker off or on; returns the Lineage.
    pub fn set_worker(&mut self, id: &str, on: bool) -> Result<String, JsError> {
        self.inner.set_worker(id, on).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// RUNS_UI: the open app's clock (`elapsed_ms`): rest, then runs, unwatched; a run in flight stays
    /// in flight. Returns the Advance (the runs it finished, the run under way).
    pub fn advance(&mut self, elapsed_ms: f64) -> String {
        js(&self.inner.advance(elapsed_ms.max(0.0) as u64))
    }

    /// RUNS_UI: a held run re-simulated from its send (the Replay), or `null`.
    pub fn replay(&self, run_id: u32) -> String {
        js(&self.inner.replay(run_id))
    }

    /// Cut 23 §1: buy the next forge step of `weapon | armour | pack`; returns the Lineage.
    pub fn buy_kit(&mut self, slot: &str) -> Result<String, JsError> {
        riddle_core::kit::buy(&mut self.inner, slot).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }

    /// Cut 23 §1: the forge's ladders with each next step's paired forecast move.
    pub fn kit_deltas(&self) -> String {
        js(&riddle_core::kit::deltas(&self.inner))
    }

    // ---- Cut 3: ascension

    /// After the ending: a new lineage under `variant` (`no_rest | short_list | bones_only |
    /// hunted`); returns the Lineage.
    pub fn ascend(&mut self, variant: &str) -> Result<String, JsError> {
        self.inner.ascend(variant).map_err(err)?;
        Ok(js(&self.inner.lineage()))
    }
}

}
use serde_json::Value;
fn arg<'a, T: serde::Deserialize<'a>>(args: &'a [Value], i: usize) -> Result<T, String> {
    T::deserialize(args.get(i).unwrap_or(&Value::Null)).map_err(|e| format!("argument {i}: {e}"))
}
pub fn new_game() -> bridge::Game { bridge::Game::new(0) }
pub fn dispatch(g: &mut bridge::Game, method: &str, args: &[Value]) -> Result<Value, String> {
    match method {
        "version" => Ok(Value::String(bridge::version())),
        "__bridge" => Ok(Value::String("3f8f0a0b36136ab76109e489cfce56472995bb8dd28eaf3df1b2efb763c25724".into())),
        "newLineage" => { Ok(Value::String(g.new_lineage(arg(args, 0)?))) },
        "load" => { Ok(Value::String(g.load(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "save" => { Ok(Value::String(g.save())) },
        "vocabulary" => { Ok(Value::String(g.vocabulary())) },
        "setRules" => { g.set_rules(arg(args, 0)?).map_err(|e| e.to_string())?; Ok(Value::Null) },
        "loadout" => { g.loadout(arg(args, 0)?).map_err(|e| e.to_string())?; Ok(Value::Null) },
        "forecast" => { Ok(Value::String(g.forecast())) },
        "forecastRefine" => { Ok(Value::String(g.forecast_refine())) },
        "send" => { Ok(Value::String(g.send().map_err(|e| e.to_string())?)) },
        "step" => { Ok(Value::String(g.step(arg(args, 0)?))) },
        "runOffline" => { Ok(Value::String(g.run_offline(arg(args, 0)?))) },
        "runOfflineQuick" => { Ok(Value::String(g.run_offline_quick(arg(args, 0)?))) },
        "runOfflineSlice" => { Ok(Value::String(g.run_offline_slice(arg(args, 0)?, arg(args, 1)?))) },
        "death" => { Ok(Value::String(g.death(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "deathDeltas" => { Ok(Value::String(g.death_deltas(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "buy" => { Ok(Value::String(g.buy(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "buyUnlockGold" => { Ok(Value::String(g.buy_unlock_gold(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "lineage" => { Ok(Value::String(g.lineage())) },
        "exportRules" => { Ok(Value::String(g.export_rules())) },
        "importRules" => { Ok(Value::String(g.import_rules(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "unlocks" => { Ok(Value::String(g.unlocks())) },
        "unlockDeltas" => { Ok(Value::String(g.unlock_deltas())) },
        "setClass" => { Ok(Value::String(g.set_class(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "selectSet" => { Ok(Value::String(g.select_set(arg(args, 0)?))) },
        "setTrait" => { Ok(Value::String(g.set_trait(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "setParty" => { Ok(Value::String(g.set_party(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "setCompanionRules" => { g.set_companion_rules(arg(args, 0)?, arg(args, 1)?).map_err(|e| e.to_string())?; Ok(Value::Null) },
        "breed" => { Ok(Value::String(g.breed(arg(args, 0)?, arg(args, 1)?).map_err(|e| e.to_string())?)) },
        "hatch" => { Ok(Value::String(g.hatch(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "companionVocabulary" => { Ok(Value::String(g.companion_vocabulary(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "buySupply" => { Ok(Value::String(g.buy_supply(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "dropSupply" => { Ok(Value::String(g.drop_supply(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "clearSupplies" => { Ok(Value::String(g.clear_supplies())) },
        "supplyCatalogue" => { Ok(Value::String(g.supply_catalogue())) },
        "autoKeep" => { Ok(Value::String(g.auto_keep())) },
        "keep" => { Ok(Value::String(g.keep(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "sellVault" => { Ok(Value::String(g.sell_vault(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "insure" => { Ok(Value::String(g.insure(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "setKeepPref" => { Ok(Value::String(g.set_keep_pref(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "setLook" => { Ok(Value::String(g.set_look(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "bail" => { g.bail(); Ok(Value::Null) },
        "choose" => { Ok(Value::String(g.choose(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "setVaultPref" => { Ok(Value::String(g.set_vault_pref(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "cageForecast" => { Ok(Value::String(g.cage_forecast(arg(args, 0)?))) },
        "setRestock" => { Ok(Value::String(g.set_restock(arg(args, 0)?))) },
        "setStart" => { Ok(Value::String(g.set_start(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "startForecast" => { Ok(Value::String(g.start_forecast(arg(args, 0)?))) },
        "forkForecast" => { Ok(Value::String(g.fork_forecast(arg(args, 0)?, arg(args, 1)?))) },
        "forecastVs" => { Ok(Value::String(g.forecast_vs(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "fold" => { Ok(Value::String(g.fold())) },
        "divergence" => { Ok(Value::String(g.divergence(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "forecastMove" => { Ok(Value::String(g.forecast_move(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "swearOath" => { Ok(Value::String(g.swear_oath(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "forswearOath" => { Ok(Value::String(g.forswear_oath().map_err(|e| e.to_string())?)) },
        "forswearOathId" => { Ok(Value::String(g.forswear_oath_id(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "drawOath" => { Ok(Value::String(g.draw_oath().map_err(|e| e.to_string())?)) },
        "commission" => { Ok(Value::String(g.commission().map_err(|e| e.to_string())?)) },
        "wallEdit" => { Ok(Value::String(g.wall_edit())) },
        "seenSystems" => { Ok(Value::String(g.seen_systems())) },
        "setOrders" => { Ok(Value::String(g.set_orders(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "equipPackage" => { Ok(Value::String(g.equip_package(arg(args, 0)?, arg(args, 1)?).map_err(|e| e.to_string())?)) },
        "unequipPackage" => { Ok(Value::String(g.unequip_package(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "pickTemperament" => { Ok(Value::String(g.pick_temperament(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "spendLevel" => { Ok(Value::String(g.spend_level(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "revokeDrill" => { Ok(Value::String(g.revoke_drill(arg(args, 0)?, arg(args, 1)?).map_err(|e| e.to_string())?)) },
        "packageOptions" => { Ok(Value::String(g.package_options(arg(args, 0)?))) },
        "bankDeposit" => { Ok(Value::String(g.bank_deposit(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "bankWithdraw" => { Ok(Value::String(g.bank_withdraw(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "swapQuest" => { Ok(Value::String(g.swap_quest().map_err(|e| e.to_string())?)) },
        "selectBloodline" => { Ok(Value::String(g.select_bloodline(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "addBloodline" => { Ok(Value::String(g.add_bloodline().map_err(|e| e.to_string())?)) },
        "upgradeHero" => { Ok(Value::String(g.upgrade_hero(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "buildTown" => { Ok(Value::String(g.build_town(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "hire" => { Ok(Value::String(g.hire(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "promote" => { Ok(Value::String(g.promote(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "openChest" => { Ok(Value::String(g.open_chest().map_err(|e| e.to_string())?)) },
        "setWorker" => { Ok(Value::String(g.set_worker(arg(args, 0)?, arg(args, 1)?).map_err(|e| e.to_string())?)) },
        "advance" => { Ok(Value::String(g.advance(arg(args, 0)?))) },
        "replay" => { Ok(Value::String(g.replay(arg(args, 0)?))) },
        "buyKit" => { Ok(Value::String(g.buy_kit(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "kitDeltas" => { Ok(Value::String(g.kit_deltas())) },
        "ascend" => { Ok(Value::String(g.ascend(arg(args, 0)?).map_err(|e| e.to_string())?)) },
        "__validateBalance" => { riddle_core::balance::parse(arg(args, 0)?).map(|_| Value::Null) },
        "__balance" => Ok(Value::String(serde_json::to_string(riddle_core::balance::get()).unwrap())),
        _ => Err(format!("unknown engine method {method}")),
    }
}
